micronaut:
  application:
    name: nexus-application
  server:
    port: 6788
  http:
    services:
      insee:
        url: https://api.insee.fr
    wildcard: /**

rabbitmq:
  exchange:
    insee:
      sirene: sirene
  queue:
    insee:
      sirene-search: sirene.search.q
  binding:
    insee:
      sirene-search: sirene.search.b
  uri: amqp://localhost:5672
  username: guest
  password: guest
      sirene-search: sirene-search-b

insee:
  api:
    token: /token
  consumer-key: l20m5bog7Vo4VRFYy55SLv5685wa
  consumer-secret: b1FqyKenafwZIEiEevl4BUSb_8Ma

siren:
  api:
    prefix: /entreprises/sirene
    version-3: /V3
    version-3-11: /V3.11
    info: /informations
    sirene-search: /siren