micronaut:
  application:
    name: dig-application
  server:
    port: 5666
    cors:
      enabled: true

  http:
    services:
      insee:
        url: https://api.insee.fr
    wildcard: /**

rabbitmq:
  exchange:
    dig: dig-exc
  queue:
    insee:
      sirene:
        search-request: sirene.historicizedSearch-request.queue
        search-response: sirene.historicizedSearch-response.queue
      siret:
        part-search: siret.part-search.queue
  binding:
    insee:
      sirene:
        search-request: sirene.historicizedSearch-request.binding
        search-response: sirene.historicizedSearch-response.binding
      siret:
        part-search: siret.part-search.binding
  uri: amqp://localhost:5672
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}

insee:
  api:
    token: /token
  consumer-key: ${SIRENE_CONSUMER_KEY}
  consumer-secret: ${SIRENE_CONSUMER_SECRET}

sirene:
  api:
    prefix: /entreprises/sirene
    version-3: /V3
    version-3-11: /V3.11
    info: /informations
    sirene-search: /siren
    siret-search: /siret