version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    env_file:
      - ~/.docker/rabbitmq/rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - dig_net
  open-data-nexus:
    image: open-data-nexus:latest
    env_file:
      - ~/.docker/nexus.env
    volumes:
      - ~/.docker/od-nexus/data/:/var/lib/open-data-nexus/
      - ~/.docker/od-nexus/log/:/var/log/open-data-nexus
    networks:
      - dig_net
  dig-bff:
    image: dig-bff:latest
    env_file:
      - ~/.docker/bff.env
    volumes:
      - ~/.docker/bff/data/:/var/lib/bff/
      - ~/.docker/bff/log/:/var/log/bff
    networks:
      - dig_net
networks:
  dig_net:
    driver: bridge