micronaut:
  application:
    name: verification
  http:
    services:
      insee:
        url: https://api.insee.fr
    wildcard: /**

insee:
  api:
    token: /token
  consumer-key: l20m5bog7Vo4VRFYy55SLv5685wa
  consumer-secret: b1FqyKenafwZIEiEevl4BUSb_8Ma

siren:
  api:
    prefix: /entreprises/sirene/V3
    info: /informations
    siren-search: /siren