version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_java_net

networks:
  rabbitmq_java_net:
    driver: bridge