micronaut:
  application:
    name: skilld-bff
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

rabbitmq:
  exchange:
    insee: insee
  queue:
    insee:
      sirene-search: sirene-search-q
  binding:
    insee:
      sirene-search: sirene-search-b