micronaut:
  server:
    port: 7689
  application:
    name: bff-application
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

rabbitmq:
  exchange:
    insee:
      sirene: sirene
  queue:
    insee:
      sirene-search: sirene.search.q
  binding:
    insee:
      sirene-search: sirene.search.b
  uri: amqp://localhost:5672
  username: ${RABBITMQ_USERNAME}:guest
  password: ${RABBITMQ_PASSWORD}:guest